### ISSUE TITLE
Can't find datasets.

### ISSUE THREAD

**Issue by paleomoon** [sam575/axial-gan#1]
Hi, thank you for your excellent work, but I can't find the datasets in the Internet, can you share it? Just for the purpose of research, thanks!

**Comment by hgzjy25** [comment]
Hi, can you share a link with me? I can't find any download link for this dataset. Thanks.
My email: hgzjy25@gmail.com

**Comment by paleomoon** [comment]
@hgzjy25 sorry I didn't get the dataset.
